baseURL = 'https://michael-olagbemiro.github.io/'
languageCode = 'en-us'
title = 'Michael Olagbemiro'
theme = 'PaperMod'

[params]
  author = 'Michael Olagbemiro'
  description = 'Network infrastructure engineer. RoCE, BGP, distributed systems.'
  disableSpecial1stPost = true
  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = false
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 2